//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Mandant
    {
        public long id { get; set; }
        public string Number { get; set; }
        public Nullable<bool> Aktiv { get; set; }
        public string Company_name { get; set; }
        public string Street_House_number { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Nation { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Datemodified { get; set; }
        public string Modifiedby { get; set; }
        public string Unique_ID { get; set; }
        public Nullable<bool> Mandant_Type { get; set; }
        public string Plugin_Access { get; set; }
        public string Client_Id { get; set; }
        public Nullable<int> Operating_mode { get; set; }
        public string RequestorTIN { get; set; }
        public Nullable<int> two_factor_authentication { get; set; }
        public string addressSupplement1 { get; set; }
        public string addressSupplement2 { get; set; }
        public string addressSupplement3 { get; set; }
        public Nullable<int> unique_mandantid { get; set; }
    }
}
