//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryMaster
    {
        public long id { get; set; }
        public string CountryNameCode { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string status { get; set; }
        public string dwjRegion { get; set; }
    }
}
