//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dowjones_Record_Setting
    {
        public long id { get; set; }
        public Nullable<int> Total_Count { get; set; }
        public Nullable<int> Remaining_Count { get; set; }
        public Nullable<int> status { get; set; }
        public string Creared_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Mandantid { get; set; }
        public string Mandant_name { get; set; }
        public string SearchStatus { get; set; }
        public Nullable<int> used_count { get; set; }
    }
}
