//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dowjones_Search_Config_Single_Search
    {
        public int SearchID { get; set; }
        public string MentodId { get; set; }
        public string NameSearch { get; set; }
        public string PersonSearch { get; set; }
        public string EnitySearch { get; set; }
        public string IDTypeSearch { get; set; }
        public Nullable<System.DateTime> Config_Date { get; set; }
        public string SearchType { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
        public string created_by { get; set; }
    }
}
