//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dowjones_TrademonkeyEntities2 : DbContext
    {
        public dowjones_TrademonkeyEntities2()
            : base("name=dowjones_TrademonkeyEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dowjones_Search_Config_Single_Search> dowjones_Search_Config_Single_Search { get; set; }
        public DbSet<dowjones_Search_Result_Details> dowjones_Search_Result_Details { get; set; }
        public DbSet<downjonws_check_countrylist> downjonws_check_countrylist { get; set; }
    }
}
