//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class downjonws_check_countrylist
    {
        public string MasterName { get; set; }
        public string id { get; set; }
        public string descriptor { get; set; }
        public string iso_alpha2 { get; set; }
        public string iso_alpha3 { get; set; }
        public string downjonws_flag { get; set; }
        public long Unique_ID { get; set; }
    }
}
