//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdecApp_Trade_MonkeyEntities : DbContext
    {
        public EdecApp_Trade_MonkeyEntities()
            : base("name=EdecApp_Trade_MonkeyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_Mandant> Admin_Mandant { get; set; }
        public DbSet<Dowjones_Record_Setting> Dowjones_Record_Setting { get; set; }
        public DbSet<Error_Log> Error_Log { get; set; }
        public DbSet<SearchLookup> SearchLookup { get; set; }
        public DbSet<Selected_Users> Selected_Users { get; set; }
        public DbSet<Userthreshold> Userthreshold { get; set; }
    }
}
