//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchLookup
    {
        public long Id { get; set; }
        public string ReferenceNumber { get; set; }
        public string MandantId { get; set; }
        public string UserName { get; set; }
        public string search_keyword { get; set; }
        public string Street { get; set; }
        public string Ort { get; set; }
        public string Plz { get; set; }
        public string Land { get; set; }
        public string listStatus { get; set; }
        public string Reasons { get; set; }
        public string SalseTaxId { get; set; }
        public string UserWhiteSearchStatus { get; set; }
        public string statusInApplication { get; set; }
        public string statusInUser { get; set; }
        public Nullable<System.DateTime> searchedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
        public string MandantName { get; set; }
        public string batchname { get; set; }
        public string deleteStatus { get; set; }
        public string ResultList { get; set; }
        public string ResultListDisp { get; set; }
        public Nullable<bool> eVVreset { get; set; }
        public string gep_List { get; set; }
        public Nullable<System.DateTime> WLsearchdate { get; set; }
        public string ExistingWl { get; set; }
        public Nullable<int> File_Mode { get; set; }
        public string ResultXml { get; set; }
        public string searchtype { get; set; }
        public string batchid { get; set; }
        public string SAN { get; set; }
        public string dowjones { get; set; }
        public string dowjones_RecStatus { get; set; }
        public string User_Responsexml { get; set; }
        public string SanList { get; set; }
        public string SanListIndi { get; set; }
        public string Fuzzyquality { get; set; }
        public string Exist_Reason { get; set; }
        public string WB_deletedby { get; set; }
        public Nullable<System.DateTime> WB_deleteddate { get; set; }
        public Nullable<int> workflowFlg { get; set; }
        public string San_Type { get; set; }
        public string VesselRegistration { get; set; }
        public string VesselMMSI { get; set; }
        public string Callsign { get; set; }
        public string Remarks { get; set; }
        public string Aircraft_SerialNumber { get; set; }
        public string AircraftModel { get; set; }
        public string Sonderstatus { get; set; }
        public string userResultAddr { get; set; }
        public string UserResultQulle { get; set; }
        public string userResSanction { get; set; }
        public string userResultAltName { get; set; }
        public string userResStatus { get; set; }
        public Nullable<int> TotalDaten { get; set; }
        public string Schlagwort { get; set; }
        public string Status_Anderung { get; set; }
        public string AktiveListen { get; set; }
        public string typeId { get; set; }
        public string DowJonesReasons { get; set; }
        public string whitelistApistatus { get; set; }
        public string Exist_Dowjones_Reason { get; set; }
        public string apiseracheddata { get; set; }
        public string Wf_Autoupdatestatus { get; set; }
        public string Scorepercentage { get; set; }
        public string sanTransaction { get; set; }
        public string Sondstatus_text { get; set; }
        public string Transaction_dj { get; set; }
        public string Bemerkung { get; set; }
        public string sender { get; set; }
        public string SanMatchword { get; set; }
        public string history { get; set; }
        public Nullable<int> unique_mandantid { get; set; }
        public string searchtype_dj { get; set; }
        public string Result_Country { get; set; }
        public string SWIFTCode { get; set; }
    }
}
