//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selected_Users
    {
        public long id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> MandantID { get; set; }
        public Nullable<int> Operating_mode { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public string Accountname { get; set; }
        public string User_Role { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Mandant_Name { get; set; }
        public string Username { get; set; }
        public Nullable<int> OTP_Verified { get; set; }
        public string consigneeTin { get; set; }
        public string User_Image { get; set; }
        public string alt_select_lan { get; set; }
    }
}
