//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userthreshold
    {
        public long id { get; set; }
        public string NamePercentage { get; set; }
        public string StreetPercentage { get; set; }
        public string CityPercentage { get; set; }
        public string MandantId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> evv_startdate { get; set; }
        public Nullable<System.DateTime> evv_endate { get; set; }
        public Nullable<bool> Contain_Search { get; set; }
        public Nullable<bool> Normal_Search { get; set; }
        public Nullable<System.DateTime> evv_reset_startdate { get; set; }
        public Nullable<System.DateTime> evv_ResetEndDate { get; set; }
        public Nullable<System.DateTime> evv_imp_startdate { get; set; }
        public Nullable<System.DateTime> evv_imp_enddate { get; set; }
        public string dispsettings { get; set; }
        public string Dow_Jones { get; set; }
        public string EvvDisplaySetting { get; set; }
        public string EvvFuzzy { get; set; }
        public string EdecDisplaySetting { get; set; }
        public string EdecFuzzy { get; set; }
        public string ApiDisplaySetting { get; set; }
        public string ApiFuzzy { get; set; }
        public string Scorepercentage { get; set; }
        public Nullable<System.DateTime> edec_date { get; set; }
        public Nullable<System.DateTime> SanApi_date { get; set; }
        public string edec_Score { get; set; }
        public string SanApi_Score { get; set; }
        public string evv_Active { get; set; }
        public string edec_Active { get; set; }
        public string sanApi_Active { get; set; }
        public string Transaktion { get; set; }
        public Nullable<int> unique_mandantid { get; set; }
    }
}
